parameters:
    my_user_provider.class: AppBundle\Security\Core\User\OAuthUserProvider

services:
    my_user_provider:
        class: AppBundle\Security\Core\User\OAuthUserProvider
        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id}, @doctrine.orm.entity_manager]

    app.form.registration:
        class: AppBundle\Form\Type\RegistrationFormType
        tags:
          - { name: form.type, alias: app_user_registration }

    app.command.read:
        class: AppBundle\Command\ReadCommand
        tags:
            - { name: console.command }
        arguments: ['read', @doctrine.orm.entity_manager, @service_container]

    app.profile.edit:
        class: AppBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: app_user_profile }
