app.index:
    path:     /
    defaults: { _controller: AppBundle:Home:index }

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

name_confirm:
    path: /name-confirm
    defaults: { _controller: AppBundle:ConfirmName:index }

name_confirm_submit:
    path: /name-confirm-submit
    defaults: { _controller: AppBundle:ConfirmName:submit }
    methods: POST

profile_show_results:
    path: /profile
    methods: GET
    defaults: { _controller: AppBundle:Account:index }

profile_update_results:
    path: /profile
    methods: POST
    defaults: { _controller: AppBundle:Account:update }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_registration_confirmed:
    pattern: /
    requirements:
        _method: GET

fos_user_registration_register:
    path: /register
    defaults: { _controller: AppBundle:Registration:register }
    requirements:
        _method: POST
