app.index:
    path:     /
    defaults: { _controller: AppBundle:Home:index }

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

